src/wallet.ts, src/wsecretjs.ts, types/wsecretjs.d.ts
- Formatting
- Ignore if not enabling when getting the chain ID
=> Temporarily fix the error when wallet is not enabled by the user

src/wsecretjs.ts, types/wsecretjs.d.ts
- Make SigningCosmWasm client optional
- Add `Result` class for handling transaction responses
=> Fix wsecretjs module

src/bootstrap.ts, src/contracts.ts, src/viewing-keys.ts, types/bootstrap.d.ts
- Add `getHeight` that maps `CosmWasmClient.getHeight` method
- Add griptape event hook `onConnectAndAlways`
- Error handling in viewing key manager
=> Add bootstrap and contracts features

src/viewing-keys.ts
- Fix when no account is found in the viewing key manager
=> Bug fixing on viewing key manager

src/bootstrap.ts, src/viewing-keys.ts, types/bootstrap.d.ts
- Let `getAddress` return undefined
=> Clean up and bug fixing

src/contracts/definitions/index.ts, src/contracts/definitions/snip-721-def.ts, src/contracts/types.ts
I added support for SNIP-721 based spec based on [this](https://github.com/SecretFoundation/SNIPs/blob/master/SNIP-721.md)
=> feat: Add support for SNIP-721 contract definition (#31)

src/modules/distribution.ts, src/modules/index.ts
=> Feat: Add distribution module (#52)

src/bootstrap.ts, src/events/accounts.ts
Featured added: #97 
UI Test:
App.js
```jsx
import { bootstrap, shutdown} from '@stakeordie/griptape.js';
return(
<button onClick={bootstrap}>Boostrap</button>
<button onClick={shutdown}>Shutdown</button>
)
```
=> feat: Add shutdown function (#97)

src/events/accounts.ts, src/events/index.ts, src/events/viewing-keys.ts, src/index.ts
=> feat: Rename Callback type on src/events/index.ts

src/events/index.ts, src/index.ts
=> feat: functions from the src/events/index.ts file

src/events/accounts.ts, src/events/index.ts, src/events/viewing-keys.ts, src/index.ts
Reverts stakeordie/griptape.js#131
=> Revert "feat: Rename Callback type on src/events/index.ts"

src/events/accounts.ts, src/events/index.ts, src/events/viewing-keys.ts, src/index.ts
=> feat:  Rename Callback type on src/events/index.ts

src/bootstrap.ts
=> feat: Add custom fees to config object

src/contracts/errors.ts, src/contracts/index.ts, src/contracts/types.ts, src/viewing-keys.ts
=> feat: add optionally set id of BaseContractProps

src/bootstrap.ts
=> feat: Remove Not connected yet error.

src/auth/account.ts, src/auth/index.ts, src/auth/permits.ts, src/auth/types.ts, src/auth/viewing-keys.ts
=> feat: Permits should be part of the Account model

src/auth/permits.ts, src/contracts/index.ts
=> Return contractAdress permit in getContext

src/bootstrap.ts
=> Add function for display of wallet name 

src/bootstrap.ts, src/contracts/index.ts
=> Remove broadcastMode configuration

src/bootstrap.ts
Branched off 0.9.6 pending secretjs upgrade for the newer blockchain
Added getCoinBalances to get balances of all coins
=> added getCoinBalances for all denoms
